// react-angular/99/hw-98-weather/src/app/weather-details/weather-details.component.ts
import { Component, Input} from '@angular/core';
import weatherInterface from 'src/weatherInterface';

@Component({
  selector: 'app-weather-details',
  templateUrl: './weather-details.component.html',
  styleUrls: ['./weather-details.component.css']
})
export class WeatherDetailsComponent {

  @Input() weather!: weatherInterface;
}

<div *ngIf="weather">
    <h1>Weather in {{weather.name}}</h1>
    <p>Temperature: {{weather.main.temp}}</p>
    <p>Humidity: {{weather.main.humidity}}</p>
</div>

// react/89/hw-89/src/WeatherDetails.js
import React from 'react'

export default function WeatherDetails(props) {
    
    let weather = props.zip;

    return (
        <>
            <div>
                <h1>Weather in {weather.name}</h1>
                <p>Temperature: {weather.main.temp}</p>
                <p>Humidity: {weather.main.humidity}</p>

            </div>      
        </>
    )
}
